id: I949149A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T20:36:45+00:00'
last_modified: '2022-06-08T02:12:15.035104+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17587
  title: གུ་རུ་དྲག་དམར་གྱི་འཕྲིན་གཞུང་དྲེགས་པ་ཟིལ་གནོན་དང་། དབང་ཆོག་མཐོང་བ་རང་གྲོལ།
    དབྱངས་ཡིག་ཚངས་དབྱངས་སེམས་ཉིད་རོལ་མཚོ་བཅས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C3C3:
      image_group_id: I1KG17959
      title: ''
      total_pages: 112
      order: 1
      base_file: C3C3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
